## Responses to SSC and Plan Team Comments on Assessments in General

> "The SSC requests that all authors fill out the risk table in 2019…" (SSC December 2018)  

A risk table has been included in this assessment.

## Responses to SSC and Plan Team Comments Specific to this Assessment

> "For the next assessment cycle, the SSC had a number of suggestions for this assessment. 
In the current assessment, having a bridge model that included both updated data and some changes to the VAST model (change in the number of knots) hampered SSC review of the impact of each of these two changes. 
The SSC registers concern with the large positive retrospective pattern in the recommended model and suggests that further investigation of this be a very high priority. 
The SSC supports the GOA GPT recommendation that authors examine survey index and age composition weighting relative to the retrospective patterns. 
The SSC also supports the GOA GPT recommendation to evaluate catchability among the retrospective runs and how age and length composition sample sizes are impacted by the patchiness of samples (frequency of occurrence). 
It may be useful to add/remove datasets one at a time and report on observed changes, as this may shine some light on the mechanism behind the change in the scale of the population and the increase in the retrospective bias. 
Additional discussion, as brought up by the GOA GPT, focusing on the biological basis for this change in the scale of the population is necessary as well. 
There is some note of some incoming recruitment of fish between 10 and 13 years old."

> "The PT recommended further work on VAST survey estimates and the SSC strongly supports this
recommendation. 
The SSC requests the assessment author justify the use of the new parameterization of VAST specifically as it relates to dusky rockfish. 
Past SSC discussions regarding the general implementation of VAST in assessments precluded a highly prescriptive approach and specifically recommended allowing for some species-specific adaptations of the VAST framework (October 2020
SSC minutes)." 

> "The SSC has also requested diagnostics to evaluate VAST model fit and suggests the author frame the discussion of these diagnostics in a species-specific manner, including consideration of the life history of the species. 
For example, the use of the delta-gamma observation model would seem to be appropriate for a species with patchy survey distribution. 
However, the implementation of this VAST-GAP recommendation resulted in a large increase in the interannual variability of the VAST survey estimates, which the SSC notes may be biologically implausible for a long-lived species such as dusky rockfish. 
The SSC also supports the GOA GPT recommendation to further explore the number of knots that are optimal for this species. 
Finally, the SSC requests that design-based estimates of survey biomass be included in comparisons with VAST model estimates. "

> "Results from Model 15.5a indicate that the estimated 2021 spawning biomass is above the estimated B40%,
placing this stock in Tier 3a for management. 
For the risk table, authors recommended a risk level of 2 for the assessment concerns category due to the large increase in model-estimated total and spawning biomass, resulting from the low variance of the geospatial model configuration coupled with the high 2019 survey biomass estimate, and the strong positive retrospective bias. 
Authors recommended a risk level of 1 for the other risk table categories. 
The SSC appreciates the implementation of the risk table for this species. 
The SSC notes that the use of the maximum ABC would nearly double the ABC from 2020 (a 93% increase). 
Given the large increase in the retrospective pattern, resulting primarily from two additional years of data but also potentially arising from new VAST parameterization, the SSC recommends a stair step approach for setting the ABC in 2021 and 2022, and therefore a reduction from the maximum ABC. Since this stock is on a biennial schedule and another full assessment will not be completed until 2022, the SSC recommends utilizing a 50% stair step for both of the 2021 and 2022 ABCs. 
Under this approach, the 2021 ABC would be set halfway between the 2020 ABC (3,676t) and the 2021 maximum ABC from the recommended model (Model 15.5a). 
This would amount to a 24% decrease from the maximum ABC for 2021. 
The 2022 ABC would be set similarly, at halfway between the 2020 ABC and the 2022 maximum ABC, resulting in a 23% decrease from the 2022 maximum ABC. 
In 2021, a partial assessment for dusky rockfish will be completed, and the projection model will be re-run with updated catch data, which will update the 2022 maximum ABC. 
The SSC recommends continuing with the 50% stair step methodology (applying a 50% stairstep between the 2020 ABC and the updated 2022 maximum ABC and the same for the estimated 2023 maximum ABC) when setting specifications until a new full assessment is presented for 2023."

