\allsectionsfont{\raggedright}
## Responses to SSC and Plan Team Comments on Assessments in General

\begin{quote}
\emph{
The SSC revised and clarified the recommendation to maintain the status quo and only produce risk tables for full assessments (rather than all assessments, as indicated in the subgroup recommendation).” (SSC, June 2021)}
\end{quote}

A risk table will be provided in the next full assessment.

\allsectionsfont{\raggedright}
## Responses to SSC and Plan Team Comments Specific to this Assessment

\begin{quote}
\emph{The SSC registers concern with the large positive retrospective pattern in the recommended model and suggests that further investigation of this be a very high priority. (January 2020)}
\end{quote}

Issues with the retrospective pattern will be explored in the 2022 full assessment.

\begin{quote}
\emph{The SSC requests the assessment author justify the use of the new parameterization of VAST specifically as it relates to dusky rockfish. Past SSC discussions regarding the general implementation of VAST in assessments precluded a highly prescriptive approach and specifically recommended allowing for some species-specific adaptations of the VAST framework (October 2020)}
\end{quote}

A suite of VAST parameterizations and associated diagnostics will be explored and provided in the 2022 full assessment.

\begin{quote}
\emph{The SSC notes that the use of the maximum ABC would nearly double the ABC from 2020 (a 93\% increase).
\textbf{Given the large increase in the retrospective pattern, resulting primarily from two additional years of data but also potentially arising from new VAST parameterization, the SSC recommends a stair step approach for setting the ABC in 2021 and 2022, and therefore a reduction from the maximum ABC.}
Since this stock is on a biennial schedule and another full assessment will not be completed until 2022, the SSC recommends utilizing a 50\% stair step for both of the 2021 and 2022 ABCs. 
\textbf{Under this approach, the 2021 ABC would be set halfway between the 2020 ABC (3,676t) and the 2021 maximum ABC from the recommended model (Model 15.5a). 
This would amount to a 24\% decrease from the maximum ABC for 2021. 
The 2022 ABC would be set similarly, at halfway between the 2020 ABC and the 2022 maximum ABC, resulting in a 23\% decrease from the 2022 maximum ABC.} 
In 2021, a partial assessment for dusky rockfish will be completed, and the projection model will be re-run with updated catch data, which will update the 2022 maximum ABC. 
\textbf{The SSC recommends continuing with the 50\% stair step methodology (applying a 50\% stairstep between the 2020 ABC and the updated 2022 maximum ABC and the same for the estimated 2023 maximum ABC) when setting specifications until a new full assessment is presented for 2023.} (January 2020)}
\end{quote}

A 50\% stair step methodology has been applied that reduces the maximum ABC for 2022 and 2023.
The model estimated maximum ABCs were 7,069 t and 6,686 t for 2022 and 2023, respectively. 
Using the 50\% stair step approach results in a 2022 maximum ABC of 5,372 t and a 2023 maximum ABC of 5,181 t.
This stair step approach will be reviewed when a full assessment is presented in 2022.