## Responses to SSC and Plan Team Comments on Assessments in General


> “The SSC supports the JGPT’s recommendation that stock assessment authors transition from the ADMB RE variants to the rema framework, which implements the same model variants in a single framework with several improvements.”(SSC, Oct 2022)  

The REMA model is currently used for catch apportionment to management areas. 
However, the current REMA model uses design-based regional survey biomass estimates as inputs. As this assessment uses VAST estimated survey biomass (i.e., model-based estimates), instead of design-based, examinations of changing to regional VAST biomass estimates as inputs to the REMA model will be explored in the next full assessment.

## Responses to SSC and Plan Team Comments Specific to this Assessment


> "SSC supports the author and GOA GPT recommendation to investigate proper variance attribution of VAST indices within the assessment model, and to explore model sensitivity to data weighting." (December 2022)

> "The SSC continues to recommend research investigating skip spawning." (December 2022)

> "The SSC recommends the authors investigate alternative apportionment methods that provide stability while also satisfying subarea-level biological concerns." (December 2022)

> "Finally, the SSC requests bubble plots of Pearson residuals for all age and length data including the sign and scale of residuals to help in evaluating fit." (December 2022)

The authors intend to explore the following for next year's (2024) operational full stock assessment: 1) investigate proper variance attribution of VAST indices, 2) examine model sensitivity to data-weighting, 3) explore uncertainty in recruitment due to skip spawning, and 4) investigate alternative apportionment methods. 

The 2024 operational full assessment will include bubble plots of Pearson residuals for age and length data to evaluate the fit.
